import { header } from "./js/header";
import { hero } from "./js/hero";
import { getMovies } from "./js/weeklyTrends";
// import { moviePopUp } from "./js/moviePopUp";
import { upComing } from "./js/upComing";
import { footer } from "./js/footer";
import { catalogFun } from "./js/catalog";
header();
hero();
getMovies();
// weeklyTrends();
// moviePopUp();
upComing();
footer();
catalogFun();
