// import { header } from "./js/header.js";
import { hero } from "./js/hero.js";
import { getMovies } from "./js/weeklyTrends.js";
// import { moviePopUp } from "./js/moviePopUp";
import { upComing } from "./js/upComing.js";
import { footer } from "./js/footer.js";
import { catalogFun } from "./js/catalog.js";
// import { myLibrary } from "./js/myLibrary";
import { scroll } from "./js/scroll.js";

// header();
hero();
getMovies();
// moviePopUp();
// weeklyTrends();
upComing();
footer();
catalogFun();
// myLibrary();
scroll();
